name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull and redeploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "/opt/HorusAPI/deploy.sh"